services:
  - type: web
    name: trumpcoin-benefit
    env: python
    buildCommand: >
      pip install -r requirements.txt && 
      mkdir -p staticfiles && 
      python manage.py collectstatic --noinput && 
      python create_superuser.py     
    startCommand: gunicorn trumpcoin_benefit.wsgi:application --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0  # Explicitly set Python version to 3.9.0 for compatibility
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: trumpcoin_benefit.render_settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: trumpcoin-db
          property: connectionString

databases:
  - name: trumpcoin-db
    databaseName: trumpcoin
    user: trumpcoin_user
    plan: free
